import type { EnemyDef } from "../types";

// ============================================================
// INIMIGOS (10 tipos) + chefe Supervisor ALPHA.
// ============================================================

export const ENEMIES: Record<string, EnemyDef> = {
  // ---- CUBOS (inimigo principal: formam paredes em formação) ----
  cube: {
    id: "cube",
    name: "Cubo",
    color: "#4aa8ff",
    hp: 10,
    speed: 0,
    radius: 19,
    damage: 10,
    xp: 1,
    credits: 1,
    behavior: "cube",
  },
  cube_tough: {
    id: "cube_tough",
    name: "Cubo Blindado",
    color: "#8a93a8",
    hp: 30,
    speed: 0,
    radius: 19,
    damage: 14,
    xp: 3,
    credits: 2,
    behavior: "cube",
  },
  cube_shooter: {
    id: "cube_shooter",
    name: "Cubo Atirador",
    color: "#ffb14d",
    hp: 16,
    speed: 0,
    radius: 19,
    damage: 8,
    xp: 3,
    credits: 2,
    behavior: "cube",
    ranged: true,
  },
  chest: {
    id: "chest",
    name: "Baú de Recompensa",
    color: "#ffc24d",
    hp: 50,
    speed: 0,
    radius: 20,
    damage: 12,
    xp: 4,
    credits: 6,
    behavior: "cube",
  },
  cube_split: {
    id: "cube_split",
    name: "Cubo Instável",
    color: "#7CFF8E",
    hp: 14,
    speed: 0,
    radius: 19,
    damage: 9,
    xp: 2,
    credits: 2,
    behavior: "cube",
    splitInto: "cube",
  },
  drone_front: {
    id: "drone_front",
    name: "Drone Frontal",
    color: "#ff7a6b",
    hp: 14,
    speed: 95,
    radius: 13,
    damage: 8,
    xp: 3,
    credits: 1,
    behavior: "rushFront",
  },
  spider: {
    id: "spider",
    name: "Roboaranha Lateral",
    color: "#ffa14d",
    hp: 18,
    speed: 130,
    radius: 14,
    damage: 9,
    xp: 4,
    credits: 1,
    behavior: "fromDoor",
  },
  guard: {
    id: "guard",
    name: "Guarda Sintético",
    color: "#9aa7b5",
    hp: 70,
    speed: 55,
    radius: 20,
    damage: 14,
    xp: 8,
    credits: 3,
    behavior: "tank",
  },
  exploder: {
    id: "exploder",
    name: "Clone Explosivo",
    color: "#ff5470",
    hp: 12,
    speed: 165,
    radius: 13,
    damage: 22,
    xp: 5,
    credits: 2,
    behavior: "exploder",
  },
  shooter: {
    id: "shooter",
    name: "Drone Atirador",
    color: "#ffd45c",
    hp: 22,
    speed: 60,
    radius: 14,
    damage: 7,
    xp: 6,
    credits: 2,
    behavior: "shooter",
    ranged: true,
  },
  turret: {
    id: "turret",
    name: "Torre Móvel",
    color: "#7fa0ff",
    hp: 95,
    speed: 30,
    radius: 22,
    damage: 12,
    xp: 10,
    credits: 4,
    behavior: "shooter",
    ranged: true,
  },
  nanomass: {
    id: "nanomass",
    name: "Nanomassa",
    color: "#7CFF8E",
    hp: 26,
    speed: 80,
    radius: 17,
    damage: 8,
    xp: 5,
    credits: 2,
    behavior: "rushPlayer",
    splitInto: "nanomass_small",
  },
  nanomass_small: {
    id: "nanomass_small",
    name: "Nanomassa Menor",
    color: "#aaffb5",
    hp: 9,
    speed: 110,
    radius: 10,
    damage: 5,
    xp: 2,
    credits: 1,
    behavior: "rushPlayer",
  },
  shieldbot: {
    id: "shieldbot",
    name: "Drone Escudo",
    color: "#5ce0ff",
    hp: 55,
    speed: 70,
    radius: 18,
    damage: 8,
    xp: 8,
    credits: 3,
    behavior: "shield",
  },
  purge_hunter: {
    id: "purge_hunter",
    name: "Perseguidor de Purga",
    color: "#ff3860",
    hp: 30,
    speed: 150,
    radius: 15,
    damage: 12,
    xp: 6,
    credits: 2,
    behavior: "pusher",
  },
  // Elite
  corridor_sentinel: {
    id: "corridor_sentinel",
    name: "Sentinela de Corredor",
    color: "#ff9f1c",
    hp: 320,
    speed: 50,
    radius: 30,
    damage: 18,
    xp: 40,
    credits: 20,
    behavior: "shooter",
    ranged: true,
  },
  // Chefe final do setor
  supervisor_alpha: {
    id: "supervisor_alpha",
    name: "Supervisor ALPHA",
    color: "#ff5470",
    hp: 2600,
    speed: 42,
    radius: 56,
    damage: 24,
    xp: 200,
    credits: 120,
    behavior: "shooter",
    ranged: true,
  },
};

// Pool de spawn comum por "tempo" (segundos) — quanto mais fundo, mais variado.
export const SPAWN_TABLE: { from: number; pool: string[] }[] = [
  { from: 0, pool: ["drone_front", "drone_front", "spider"] },
  { from: 45, pool: ["drone_front", "spider", "exploder", "shooter"] },
  { from: 90, pool: ["spider", "exploder", "shooter", "guard", "nanomass"] },
  { from: 150, pool: ["exploder", "guard", "nanomass", "shooter", "purge_hunter"] },
  { from: 220, pool: ["guard", "nanomass", "shieldbot", "purge_hunter", "turret"] },
  { from: 300, pool: ["guard", "shieldbot", "turret", "purge_hunter", "nanomass", "exploder"] },
];
