import type { WeaponDef } from "../types";

// ============================================================
// ARMAS — 8 básicas + 10 fusões (evolved).
// Cada fusão tem evolveReq (arma básica no nível máx + req).
// ============================================================

export const MAX_WEAPON_LEVEL = 5;

const W: WeaponDef[] = [
  // ---- 1. Rifle de Pulso (frontal) ----
  {
    id: "pulse_rifle",
    name: "Rifle Cadenciado",
    behavior: "frontal",
    desc: "Tiro a tiro numa boa cadência; ricocheteia 1× e atravessa cubos. Recarrega o pente.",
    color: "#5cf2ff",
    cooldown: 0.24,
    damage: 8,
    speed: 660,
    count: 1,
    pierce: 2,
    bounces: 1,
    spread: 0.05,
    mag: 12,
    reload: 1.15,
  },
  {
    id: "shotgun",
    name: "Dispersor",
    behavior: "frontal",
    desc: "Várias balas num leque por disparo; pente pequeno, recarrega.",
    color: "#ff9f4d",
    cooldown: 0.72,
    damage: 5,
    speed: 580,
    pellets: 6,
    pierce: 1,
    bounces: 0,
    spread: 0.62,
    mag: 5,
    reload: 1.5,
    range: 210, // alcance CURTO — as balas dissipam perto
  },
  {
    id: "burst",
    name: "Rajada Tripla",
    behavior: "frontal",
    desc: "Dispara 3 balas de uma vez, gastando o pente; recarrega rápido.",
    color: "#b98cff",
    cooldown: 0.46,
    damage: 9,
    speed: 720,
    burst: 3,
    pierce: 2,
    bounces: 1,
    spread: 0.13,
    mag: 3,
    reload: 0.85,
  },
  {
    id: "hammer",
    name: "Martelo de Choque",
    behavior: "melee",
    desc: "Golpeia em arco os inimigos à frente; sem munição. Melhora alcance/dano.",
    color: "#ffd65c",
    cooldown: 0.6,
    damage: 30,
    speed: 0,
    radius: 66,
    arc: 1.5,
    knockback: 120,
  },
  // ---- 2. Drone Sentinela ----
  {
    id: "drone_sentinel",
    name: "Drone Sentinela",
    behavior: "drone",
    desc: "Um drone acompanha e atira no inimigo mais próximo.",
    color: "#ffd65c",
    cooldown: 0.7,
    damage: 7,
    speed: 520,
    count: 1,
  },
  // ---- 3. Nanites (teleguiado + dano contínuo) ----
  {
    id: "nanites",
    name: "Nanites",
    behavior: "nanite",
    desc: "Nanites perseguem inimigos e causam dano ao longo do tempo.",
    color: "#7CFF8E",
    cooldown: 1.0,
    damage: 4,
    speed: 240,
    count: 2,
    duration: 3,
  },
  // ---- 4. Pulso Gravitacional (área que puxa) ----
  {
    id: "grav_pulse",
    name: "Pulso Gravitacional",
    behavior: "gravity",
    desc: "Onda que puxa e dá dano aos inimigos próximos.",
    color: "#b98cff",
    cooldown: 2.2,
    damage: 5,
    speed: 0,
    radius: 120,
    duration: 1.6,
    knockback: 60,
  },
  // ---- 5. Disco Magnético (ricochete) ----
  {
    id: "magnetic_disc",
    name: "Disco Magnético",
    behavior: "ricochet",
    desc: "Discos que ricocheteiam nas paredes do laboratório.",
    color: "#ff8cf0",
    cooldown: 1.1,
    damage: 12,
    speed: 460,
    count: 1,
    bounces: 4,
    pierce: 99,
  },
  // ---- 6. Minas de Retaguarda ----
  {
    id: "rear_mines",
    name: "Minas de Retaguarda",
    behavior: "mine",
    desc: "Solta minas atrás do personagem enquanto avança.",
    color: "#ff6b5c",
    cooldown: 1.3,
    damage: 22,
    speed: 0,
    count: 1,
    radius: 70,
    duration: 6,
  },
  // ---- 7. Corrente Tesla (cadeia) ----
  {
    id: "tesla_chain",
    name: "Corrente Tesla",
    behavior: "chain",
    desc: "Um raio pula entre inimigos próximos.",
    color: "#8cf6ff",
    cooldown: 1.4,
    damage: 8,
    speed: 0,
    chainJumps: 3,
    radius: 180,
  },
  // ---- 8. Canhão Rail (feixe perfurante) ----
  {
    id: "rail_cannon",
    name: "Canhão Rail",
    behavior: "rail",
    desc: "Feixe que atravessa inimigos em linha horizontal.",
    color: "#ffffff",
    cooldown: 1.8,
    damage: 26,
    speed: 0,
    pierce: 99,
    duration: 0.18,
  },

  // ============================================================
  // FUSÕES (10) — evolved:true, não entram no pool de armas básicas
  // ============================================================
  {
    id: "pulse_executor",
    name: "Rifle Executor",
    behavior: "frontal",
    desc: "Tiros perfuram vários inimigos e priorizam elites.",
    color: "#9cffff",
    cooldown: 0.4,
    damage: 16,
    speed: 740,
    count: 2,
    pierce: 4,
    bounces: 1,
    evolved: true,
    mods: { elitePriority: true },
  },
  {
    id: "pulse_storm",
    name: "Tempestade de Pulso",
    behavior: "frontal",
    desc: "Dispara rajadas frontais e diagonais.",
    color: "#9cffff",
    cooldown: 0.38,
    damage: 11,
    speed: 680,
    count: 2,
    pierce: 2,
    bounces: 2,
    evolved: true,
    mods: { frontalSpread: 2 },
  },
  {
    id: "rail_fragment",
    name: "Rail Fragmentado",
    behavior: "rail",
    desc: "Ao atravessar inimigos, solta fragmentos para cima e para baixo.",
    color: "#dfefff",
    cooldown: 1.5,
    damage: 30,
    speed: 0,
    pierce: 99,
    duration: 0.2,
    evolved: true,
    mods: { verticalFragments: true },
  },
  {
    id: "disc_conductor",
    name: "Disco Condutor",
    behavior: "ricochet",
    desc: "Cada ricochete solta raios elétricos.",
    color: "#ffb0f6",
    cooldown: 1.0,
    damage: 14,
    speed: 500,
    count: 1,
    bounces: 6,
    pierce: 99,
    evolved: true,
    mods: { bounceLightning: true },
  },
  {
    id: "disc_guillotine",
    name: "Guilhotina Magnética",
    behavior: "ricochet",
    desc: "O disco volta mais rápido e causa dano crítico no retorno.",
    color: "#ffb0f6",
    cooldown: 0.85,
    damage: 18,
    speed: 620,
    count: 1,
    bounces: 5,
    pierce: 99,
    evolved: true,
    mods: { returnCrit: true, boomerang: true },
  },
  {
    id: "mine_collapse",
    name: "Armadilha de Colapso",
    behavior: "mine",
    desc: "Minas puxam inimigos antes de explodir.",
    color: "#ff9b8c",
    cooldown: 1.1,
    damage: 28,
    speed: 0,
    count: 2,
    radius: 90,
    duration: 6,
    evolved: true,
    mods: { minePull: 240 },
  },
  {
    id: "mine_toxic",
    name: "Solo Contaminado",
    behavior: "mine",
    desc: "Minas deixam poças tóxicas depois da explosão.",
    color: "#b6ff7c",
    cooldown: 1.2,
    damage: 24,
    speed: 0,
    count: 1,
    radius: 80,
    duration: 6,
    evolved: true,
    mods: { mineToxic: true },
  },
  {
    id: "drone_swarm",
    name: "Colmeia Mecânica",
    behavior: "drone",
    desc: "Vários drones pequenos cercam o jogador.",
    color: "#ffe487",
    cooldown: 0.55,
    damage: 8,
    speed: 560,
    count: 4,
    evolved: true,
  },
  {
    id: "tesla_storm",
    name: "Tempestade Tesla",
    behavior: "chain",
    desc: "Correntes pulam com mais frequência e podem duplicar.",
    color: "#b0f9ff",
    cooldown: 0.9,
    damage: 10,
    speed: 0,
    chainJumps: 6,
    radius: 220,
    evolved: true,
    mods: { duplicateChance: 0.35 },
  },
  {
    id: "grav_singularity",
    name: "Micro Singularidade",
    behavior: "gravity",
    desc: "Cria pequenos buracos negros à frente do jogador.",
    color: "#cf9bff",
    cooldown: 2.4,
    damage: 9,
    speed: 0,
    radius: 150,
    duration: 2.2,
    knockback: 0,
    evolved: true,
    mods: { blackHole: true },
  },
  {
    id: "nanite_plague",
    name: "Praga Sintética",
    behavior: "nanite",
    desc: "Inimigos infectados espalham nanites ao morrer.",
    color: "#a6ff9c",
    cooldown: 0.85,
    damage: 6,
    speed: 280,
    count: 3,
    duration: 3.5,
    evolved: true,
    mods: { infectSpread: true },
  },
];

// Tabela de fusões: base (nível máx) + requisito → resultado.
export const FUSIONS: {
  result: string;
  base: string;
  req: { weapon?: string; passive?: string };
}[] = [
  { result: "pulse_executor", base: "pulse_rifle", req: { passive: "neural_aim" } },
  { result: "pulse_storm", base: "pulse_rifle", req: { passive: "area_amp" } },
  { result: "rail_fragment", base: "rail_cannon", req: { passive: "ricochet_mod" } },
  { result: "disc_conductor", base: "magnetic_disc", req: { weapon: "tesla_chain" } },
  { result: "disc_guillotine", base: "magnetic_disc", req: { passive: "cadence" } },
  { result: "mine_collapse", base: "rear_mines", req: { weapon: "grav_pulse" } },
  { result: "mine_toxic", base: "rear_mines", req: { weapon: "nanites" } },
  { result: "drone_swarm", base: "drone_sentinel", req: { passive: "drone_proc" } },
  { result: "tesla_storm", base: "tesla_chain", req: { passive: "cadence" } },
  { result: "grav_singularity", base: "grav_pulse", req: { passive: "grav_motor" } },
  { result: "nanite_plague", base: "nanites", req: { passive: "bio_cat" } },
];

export const WEAPONS: Record<string, WeaponDef> = Object.fromEntries(
  W.map((w) => [w.id, w]),
);

export const BASE_WEAPONS = W.filter((w) => !w.evolved);
